### ISSUE TITLE
[PE-D][Tester D] Invalid Phone number

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-F09-1/tp#152]
Maybe we can scope the phone numbers to valid Singapore numbers e.g. `9______`, `6_______`, as unlikely we call emergency helplines for contacting sellers/buyers. Command works if phone number is `4123` as well, and `123`.

But I understand if you are being more flexible to other foreign numbers. 

![Screenshot 2024-04-05 at 4.18.31 PM.png](https://raw.githubusercontent.com/cliftonchee/ped/main/files/ed8cbff1-a974-4269-99cd-fe3163c1c1fb.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: cliftonchee/ped#2

**Comment by felixchanyy** [comment]
TODO: Justification in UG [Overseas phone number(buyer) are allowed]
