### ISSUE TITLE
[PE-D][Tester E] View menu closed after most commands

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103-F09-1/tp#187]
After making a command, the view menu usually closes and this can be burdensome when the user tries to add multiple houses to a seller and cannot verify it without `view` many times. In this report, I tried the `addHouse` command but this problem is replicated by many other commands.

## Steps to reproduce

Preconditions: Ensure contacts empty or make sure you correct index when you `view INDEX`
Try:

1.  `addSeller n/jonnie dough p/98765432 e/johnd@example.com type/Hdb street/NiceAve 2 blk/311 level/02 unitNo/25 postal/578578 price/999999999`

2. `view 1`

3. ` addHouse n/Jonnie dough type/Condominium street/Clementi Ave 2 blk/N/A level/02 unitNo/5 postal/578578 price/10000`

## Expected

View menu should remain open and the house that was just added displayed.

## Actual

View menu closes after adding the new house

Before adding house:
![Screenshot 2024-04-05 at 6.25.00 PM.png](https://raw.githubusercontent.com/jerremyng/ped/main/files/568151de-85c2-464f-a576-67debd5ff2cb.png)

After adding house:

![Screenshot 2024-04-05 at 6.27.17 PM.png](https://raw.githubusercontent.com/jerremyng/ped/main/files/01d0ce70-b0a2-4737-bddb-f1cb46606f9d.png)

## Suggestion

Group may want to streamline the app and allow that `view` menu to stay open even after making different commands.

``

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: jerremyng/ped#7

**Comment by felixchanyy** [comment]
TODO: add justification in UG
