### ISSUE TITLE
[PE-D][Tester E] Matching process is not explained well in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103-F09-1/tp#198]
![Screenshot 2024-04-05 at 11.13.05 PM.png](https://raw.githubusercontent.com/jerremyng/ped/main/files/d833f2f1-533f-4f00-8856-ba5f12e237c4.png)

As a user, I want to make sure all matches are found, but if the matching process is not clear, I cannot verify that the app works as I expect.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: jerremyng/ped#9

**Comment by felixchanyy** [comment]
DONE
